# Site settings
title: christian.codes
header-img: img/home-bg.png
email: whitesidescr@gmail.com
copyright_name: crwhitesides
description: > # this means to ignore newlines until "baseurl:"
  One line at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: crwhitesides
github_username:  crwhitesides
learn_profile: crwhitesides
email_username: whitesidescr@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
